# Generated by Django 4.1.7 on 2023-04-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_portimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_text', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
