# Generated by Django 4.1.7 on 2023-04-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_aboutfirstimage_aboutsecondimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryText', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
